feature/typography
estartando-devs/ajudaqui pull request #4
Opened 2021-07-31 19:44 UTC by ramonxm

Fiquei com algumas dúvidas se essa seria a melhor forma para a aplicação, pelo menos o switch case não sei se ficou a melhor solução, o que achas?

2021-07-31 21:13 UTC, jonataspinto requested changes
Fala Ramon, dessa forma o componente seria sempre um h1, aí perde a parte de semântica. Da uma olhada [nesse cara](https://github.com/estartando-devs/site/tree/develop/src/components/elements/Typography)

2021-08-01 01:00 UTC, ramonxm commented
atualizações feitas! tive alguns problemas com o lint, botei tudo required no prop-type pq parecia q meu defaultprops n estavam funcionando, caso encontre alguma solução, manda ai o/

2021-08-01 02:09 UTC, jonataspinto requested changes

2021-08-01 02:09 UTC, jonataspinto commented on src/components/Typography/index.jsx
> +  Typography.propTypes = {
Fala mano, tenta colocar fora do componente e testa novamente a questão de default props.

2021-08-01 02:11 UTC, ramonxm commented on src/components/Typography/index.jsx
> +  Typography.propTypes = {
Eu tentei assim, mas aí deu erro de lint 😐

2021-08-01 02:14 UTC, ramonxm commented on src/components/Typography/index.jsx
> +  Typography.propTypes = {
Mas vou tentar again

2021-08-01 02:36 UTC, ramonxm commented on src/components/Typography/index.jsx
> +  Typography.propTypes = {
tinha refeito e tinha 'funcionado', dei restart e o lint zoou

2021-08-01 02:56 UTC, jonataspinto commented on src/components/Typography/index.jsx
> +  Typography.propTypes = {
qual o erro?

2021-08-01 02:58 UTC, ramonxm commented on src/components/Typography/index.jsx
> +  Typography.propTypes = {
ele diz que não defini um defaultprops pra nenhuma delas

2021-08-01 02:59 UTC, ramonxm commented on src/components/Typography/index.jsx
> +  Typography.propTypes = {
A minha solução tinha sido botar required pra todas, mas é meio zoado, quando eu defino o defaultProps parece que não rola

2021-08-01 03:05 UTC, jonataspinto commented on src/components/Typography/index.jsx
> +  Typography.propTypes = {
ha sim. Faz o seguinte.

coloca isso no lint ` "react/require-default-props": "off"` e coloca a validaçao do proptypes fora do componente.

2021-08-01 03:09 UTC, jonataspinto requested changes

2021-08-01 03:09 UTC, jonataspinto commented on src/components/Typography/index.jsx
> +  Typography.propTypes = {
outro detalhe é que o componente esta direto no index. faltou o Typography.jsx.

2021-08-01 03:36 UTC, jonataspinto approved these changes
Vamos 🔥 ⚡

2021-08-01 03:36 UTC, merged