Feature/button component
estartando-devs/ajudaqui pull request #5
Opened 2021-07-31 19:46 UTC by AidaFig

- Button Component criado
- Props criadas para atender os estilos diferentes de buttons
- Evento de clique adicionado

2021-07-31 21:21 UTC, jonataspinto requested changes

2021-07-31 21:21 UTC, jonataspinto commented on src/components/ButtonComponent/index.jsx
> +  const Click = () => {
Fala @AidaFig dessa forma não conseguiremos usar o evento de click lá fora. A função que será executada no onClick tem que vir de props.

2021-07-31 21:21 UTC, jonataspinto commented on src/components/ButtonComponent/index.jsx
> +    <div>
Essa div eu acho que é dispensável, podemos retornar o Button direto.

2021-07-31 21:21 UTC, jonataspinto commented on src/components/ButtonComponent/index.jsx
> +      <S.Button type="button" width={width} border={border} color={color} shadow={shadow} background={background} onClick={Click}>{children}</S.Button>
**Uma dica**

Quando temos props que só serão repassadas sem nenhum tratamento, utilizamos o spread. 

[Da uma olhadinha aqui](https://medium.com/coding-at-dawn/how-to-pass-all-props-to-a-child-component-in-react-bded9e38bb62) :smiley:

2021-08-01 18:12 UTC, AidaFig commented
- onClick corrigido
- <div> removida
- spread adicionada

2021-08-01 18:38 UTC, jonataspinto approved these changes
Boa @AidaFig!

2021-08-01 18:51 UTC, merged