feat: Variation of the evaluation screen made for the volunteer
estartando-devs/ajudaqui pull request #74
Opened 2021-08-20 19:35 UTC by Rafaella-Almeida

Feita a variação da tela de avaliação para o voluntario

2021-08-20 21:17 UTC, jonataspinto requested changes

2021-08-20 21:17 UTC, jonataspinto commented on src/pages/ScreenEvaluation/ScreenEvaluation.jsx
> +      {profileType === "elderly" ? (
no lugar desse `"elderly"` pode user `PROFILES_TYPES.ELDERLY` lembra?

2021-08-21 15:28 UTC, Rafaella-Almeida commented on src/pages/ScreenEvaluation/ScreenEvaluation.jsx
> +      {profileType === "elderly" ? (
okay, lembro sim
 Já arrumei aqui

2021-08-21 15:36 UTC, ramonxm approved these changes
🔥

2021-08-21 18:12 UTC, ramonxm approved these changes

2021-08-21 18:12 UTC, ramonxm approved these changes

2021-08-21 18:13 UTC, ramonxm approved these changes

2021-08-22 18:02 UTC, jonataspinto approved these changes

2021-08-22 18:09 UTC, merged